### ISSUE TITLE
Could not find a package configuration file provided by "LibEPOS2"

### ISSUE THREAD

**Issue by inksci** [uos/katana_driver#24]
You know that if I want to use katana_driver, I must install uos-ros-pkg first.
I am in trouble following the instructions as bellow for installation of uos-ros-pkg.
```
# create catkin workspace
. /opt/ros/indigo/setup.bash
mkdir -p ~/ros-indigo/src/
cd ~/ros-indigo/src/
wstool init
wstool merge https://raw.githubusercontent.com/uos/uos_rosinstalls/master/uos-public-indigo-wet.rosinstall
wstool update

# install dependencies
rosdep update
rosdep install --from-paths ./ -i -y --rosdistro indigo

# build all packages
catkin_init_workspace
cd ..
catkin_make
. ~/ros-indigo/devel/setup.bash

# make sure the correct setup.bash is sourced in each new shell
echo ". ~/ros-indigo/devel/setup.bash" >> ~/.bashrc
```

when I run
```
catkin_make
```
I get error as bellow:
```
CMake Error at volksbot_driver/CMakeLists.txt:14 (find_package):
  Could not find a package configuration file provided by "LibEPOS2" with any
  of the following names:

    LibEPOS2Config.cmake
    libepos2-config.cmake

  Add the installation prefix of "LibEPOS2" to CMAKE_PREFIX_PATH or set
  "LibEPOS2_DIR" to a directory containing one of the above files.  If
  "LibEPOS2" provides a separate development package or SDK, be sure it has
  been installed.


-- Configuring incomplete, errors occurred!
See also "/home/exbot/ros-indigo/build/CMakeFiles/CMakeOutput.log".
See also "/home/exbot/ros-indigo/build/CMakeFiles/CMakeError.log".
Invoking "cmake" failed
```
How can I solve this problem? Or where can I find the information about 'LibEPOS2', and thanks!

**Comment by jspricke** [comment]
That sounds completely out of date, sorry. Please use the packages coming with ROS, i.e. `apt install ros-kinetic-katana-driver` (or whatever ROS release you are using).

@mintar can you confirm and maybe change the instructions in the wiki?

**Comment by mintar** [comment]
Just to add: For katana_driver, you don't need libepos at all. You would only need libepos for the volksbot_driver; installation instructions are here: http://wiki.ros.org/volksbot_driver

**Comment by mintar** [comment]
... and for the katana_driver, the only instruction needed is indeed what @jspricke wrote (`apt install ros-kinetic-katana-driver`, or `apt-install ros-indigo-katana-driver` etc.).

**Comment by mintar** [comment]
I've updated the wiki page and also added a link to the calvin_robot repository as an example how to run it in Gazebo.
