### ISSUE TITLE
Can't initialize robot

### ISSUE THREAD

**Issue by schwarzp93** [uos/katana_driver#25]
Hi Guys :)

I tried to use the Katana Driver for a Katana 450 with ROS Kinetic. When running katana.launch, everything seems to work until the part where the katana.cpp tries to init the robot.
--> All the positive ROS_INFO feedbacks are displayed, but when it comes to initializing, nothing is shown (neither `ROS_ERROR("Exception during initialization")`, nor `ROS_INFO("success: katana initialized")` ...)

The last thing the console shows is `ROS_INFO("success: communication with Katana initialized")`. After some minutes there is an Error (broken pipe), but I suppose, that's due to a connection time out?!

Does someone have a clue, what I could be doing wrong?

Thanks in advance, Philipp

**Comment by mintar** [comment]
Hi Philipp, unfortunately I haven't used the Katana in years, so I'm afraid I can't help you.
