### ISSUE TITLE
GazeboRosKatanaGripper updates dynamic_reconfigure parameters in each iteration

### ISSUE THREAD

**Issue by v4hn** [uos/katana_driver#7]
Hey Martin,

Thank you for doing such a great job maintaining drivers for the katana! :-)

See the subject for the problem I want to report.

The result of this behaviour are gigabytes of roslog explaining
that gazebo updated /katana/gripper_pid/\* parameters every .002 seconds
and most likely there's a significant performance impact.

The relevant code lines are
katana_gazebo_plugins/src/gazebo_ros_katana_gripper.cpp:165-171

**Comment by mintar** [comment]
Fixed. Now the Gazebo simulation is also back to the speed it had in Fuerte (3-4x faster than previously).
